### ISSUE TITLE
Are you sure the MIT license is the correct license?

### ISSUE THREAD

**Issue by EamonNerbonne** [thecoderok/Unidecode.NET#11]
You state this is derived from https://bitbucket.org/DimaStefantsov/unidecodesharpfork, and that has no license (is this a legal copy?).  Then again, that author was probably being careless, since they do list the history of the project, and unidecodesharpfork states it's derived from https://pypi.org/project/Unidecode/ which fairly quickly switched to a GPL license.

On what basis do you believe you have the appropriate licenses to be able to release this under the MIT license?

Obviously this isn't just your fault; unidecode licensing history is pretty messy :-/

**Comment by phnx47** [comment]
I looked many forks.

I wrote information about license in [Readme](https://github.com/thecoderok/Unidecode.NET#license).

Thank you!
