### ISSUE TITLE
Publish last version to Nuget

### ISSUE THREAD

**Issue by phnx47** [thecoderok/Unidecode.NET#2]
Or you can give me access and I can do it.

**Comment by thecoderok** [comment]
Thank you Sergey! 
What is your username on Nuget (so I can add you to the list of owners)

**Comment by phnx47** [comment]
My username: phnx47.
Access to the repository would allow me to maintain the code. I can also set up AppVeyor.

**Comment by thecoderok** [comment]
Ok, you should have the access to the package

**Comment by phnx47** [comment]
Thanks!
