### ISSUE TITLE
Make Unidecode.NET configurable

### ISSUE THREAD

**Issue by roman-yagodin** [thecoderok/Unidecode.NET#4]
Unidecode.NET should be configurable as there could be more than one variant of Unicode to ASCII mapping rules (see e.g. https://en.wikipedia.org/wiki/BGN/PCGN_romanization_of_Russian).

At least next two things should be done to achieve this:
1. Allow to pass characters dictionary to `Unidecode` extension methods (as an optional parameter or via additional signatures).
2. Add method to get a deep copy of the default dictionary to be able to adjust a small portion of it.

It also would be nice to have some way to easily access culture-specific parts in the dictionary.

**Comment by roman-yagodin** [comment]
Any reason behind closing this?

**Comment by phnx47** [comment]
I researched history. We converted characters from [Perl](https://metacpan.org/pod/distribution/Text-Unidecode/lib/Text/Unidecode.pm) distributed under the Perl license(GPL-2).

I think here better use characters as is.

But, if you need make better library, you make new library. For example, for better support Russian language, make special for Russian(https://en.wikipedia.org/wiki/BGN/PCGN_romanization_of_Russian). Or make big library when you can use many configurations
