### ISSUE TITLE
Why is 一 transliterated to [?]

### ISSUE THREAD

**Issue by Jogai** [thecoderok/Unidecode.NET#6]
A chinese one is converted to [?]. Is it just my machine or is it a default in the library?

**Comment by phnx47** [comment]
It is default

**Comment by Jogai** [comment]
Wouldnt it be a nice addition? Seems possible: https://ltl-taiwan.com/chinese-numbers/

**Comment by phnx47** [comment]
I researched history. We converted characters from [Perl](https://metacpan.org/pod/distribution/Text-Unidecode/lib/Text/Unidecode.pm) distributed under the Perl license(GPL-2).

I think here better use characters as is.

For custom, better make new library.
