### ISSUE TITLE
ö changed in v1.3

### ISSUE THREAD

**Issue by Vdm88** [thecoderok/Unidecode.NET#8]
Hello, 
It's kind of strange that you changed the ö to oe in version 1.3 compared to version 1.2 where ö was o.
And nothing in the release notes about this.

Ex v1.2 "Köln" =""Koln"
v1.3 "Köln" = "Koeln" 

This kind of messes up with our canonical url.

**Comment by RubenMateus** [comment]
any news from this?

**Comment by Vdm88** [comment]
I just reverted to v1.2

**Comment by phnx47** [comment]
I just accepted this PR: https://github.com/thecoderok/Unidecode.NET/pull/5 

Is it wrong?

**Comment by phnx47** [comment]
https://github.com/thecoderok/Unidecode.NET/blob/1.3.0/test/UnidecoderTest.cs

Checked Russian and German in tests only

**Comment by Vdm88** [comment]
Well i used the lib to fold the accents in our canonical url. Then from the version 1.3
v1.2 "Köln" =""Koln"
v1.3 "Köln" = "Koeln"

So in terms of SEO it generated a new url since i had 
....controller/businessname_koln 
and on v1.3 i had
....controller/businessname_koeln 
Which was bad for us.

So either i remain to v1.2 or i need to use something else to do the job.

**Comment by tuukka-kataja** [comment]
> I just accepted this PR: #5
> 
> Is it wrong?

For Finnish, the correct (as in, expected) ASCII transliteration is 'ä' -> 'a', 'ö' -> 'o' and 'å' -> 'a'. I strongly suspect that this is also true for the scandinavian languages (Swedish, Norwegian, Islandic & Danish).

We are using Unidecode.NET to transliterate people's names to be used in usernames. The "German" transliteration of 'ä' -> 'ae' creates transliterations that simply look wrong to a Finnish person. For example, a common Finnish surname of 'Hämäläinen' is transliterated to 'Haemaelaenen', which not only looks foreign to a Finn, but would also be pronounced completely differently (the expected transliteration would be 'Hamalainen').

I'm not sure there is a simple resolution to this if 'ä' -> 'ae' etc. are the correct transliterations for German and other languages, but for us this change has forced us to revert to using version 1.2

**Comment by phnx47** [comment]
I confirm, that problems after 1.2 version.

I will update all codes and fix it.

**Comment by phnx47** [comment]
I updated characters from original library in 2.0.0. Maybe it is can help.
